#' Example differential expression heatmap dataset
#'
#' A simulated differential expression analysis dataset containing
#' log2 fold-change and adjusted p-value statistics for four genes
#' across four cell types.
#'
#' The dataset is intended for demonstrating and testing
#' `make_dea_lfc_heatmap()`.
#'
#' The data were specifically designed to illustrate significance
#' annotations within heatmap tiles. Several genes are statistically
#' significant in some cell types while remaining non-significant in
#' others.
#'
#' @format A data frame with 16 rows and 4 variables:
#' \describe{
#'   \item{cell_type}{
#'   Cell type annotation with four levels:
#'   `"Cell-type A"`, `"Cell-type B"`,
#'   `"Cell-type C"`, and `"Cell-type D"`.
#'   }
#'   \item{gene}{
#'   Simulated gene identifier.
#'   }
#'   \item{log2FoldChange}{
#'   Simulated log2 fold-change value.
#'   }
#'   \item{padj}{
#'   Simulated adjusted p-value.
#'   }
#' }
#'
#' @details
#' The dataset contains four genes (`gene1`–`gene4`) evaluated
#' across four cell types.
#'
#' Several genes exhibit cell-type-specific significance patterns.
#' For example, `gene1` is highly significant in Cell-type A and
#' Cell-type B but non-significant in Cell-type C and Cell-type D.
#' Similarly, `gene3` and `gene4` contain mixtures of significant
#' and non-significant adjusted p-values across cell types.
#'
#' These patterns allow heatmaps generated by
#' `make_dea_lfc_heatmap()` to demonstrate:
#' \itemize{
#'   \item Positive and negative log2 fold-change values.
#'   \item Multiple significance levels represented by
#'   asterisks (`*`, `**`, `***`).
#'   \item Genes that are significant in some cell types
#'   but not others.
#'   \item Cell-type-specific differential expression patterns.
#' }
#'
#' Example significance patterns include:
#' \itemize{
#'   \item `gene1`: significant in Cell-type A and Cell-type B,
#'   non-significant in Cell-type C and Cell-type D.
#'   \item `gene3`: highly significant in Cell-type C,
#'   weakly significant in Cell-type D,
#'   and non-significant elsewhere.
#'   \item `gene4`: significant in Cell-type C and Cell-type D,
#'   non-significant in Cell-type A and Cell-type B.
#' }
#'
#' @source Simulated data.
#'
#' @examples
#' head(dea_heatmap_df)
#'
"dea_heatmap_df"
