#' Create Dimensionality Reduction Plots
#'
#' @description
#' Generates faceted scatter plots for reduced dimensionality representations
#' (e.g., UMAP, t-SNE, PCA) across datasets or modalities, color-coded by cell
#' type or cluster annotations.
#'
#' @param df A \code{data.frame} (or tibble) containing reduced dimension coordinates,
#'   cell type annotations, and dataset/facet grouping variables.
#' @param dim_1 Character string. The column name in \code{df} corresponding to the
#'   x-axis coordinates. Default is \code{"UMAP1"}.
#' @param dim_2 Character string. The column name in \code{df} corresponding to the
#'   y-axis coordinates. Default is \code{"UMAP2"}.
#' @param ct_col Character string. The column name in \code{df} containing cell type
#'   or cluster identifiers used for coloring points. Required.
#' @param dataset_col Character string. The column name in \code{df} containing
#'   dataset or modality identifiers used for faceting. Required.
#' @param axis_label_base Character string. Optional base string for axis labels
#'   (e.g., \code{"UMAP"} produces labels \code{"UMAP1"} and \code{"UMAP2"}). If
#'   \code{NULL} (default), uses \code{dim_1} and \code{dim_2} directly as axis labels.
#' @param color_label Character string. Title for the legend. If \code{NULL}
#'   (default), defaults to \code{ct_col}.
#' @param color_vec Character vector. Vector of hex color codes or color names.
#'   Can be named (where names match values in \code{ct_col}) or unnamed (matching
#'   the length/order of unique cell types). If \code{NULL} (default), a default
#'   hue palette generated by \code{\link[scales]{hue_pal}} is used.
#' @param point_size Numeric. Size of the scatter plot points. Default is \code{0.05}.
#' @param point_alpha Numeric. Transparency value for scatter points between 0
#'   (transparent) and 1 (opaque). Default is \code{0.8}.
#' @param base_font_size Numeric. Base font size passed to \code{\link[ggplot2]{theme_classic}}.
#'   Default is \code{14}.
#'
#' @return A \code{\link[ggplot2]{ggplot}} object containing the faceted dimensional
#'   reduction plot. Can be further customized using standard \code{ggplot2} layers.
#'
#' @importFrom rlang .data
#' @export
#'
#' @examples
#'
#' # 1. Faceted plot split by assay modality
#' make_reduced_dim_plots(
#'   df = reduced_dim_df,
#'   dim_1 = "UMAP1",
#'   dim_2 = "UMAP2",
#'   ct_col = "cell_type",
#'   dataset_col = "modality",
#'   point_size = 1
#' )

make_reduced_dim_plots <- function(
    df,
    dim_1 = "UMAP1",
    dim_2 = "UMAP2",
    ct_col,
    dataset_col,
    axis_label_base = NULL,
    color_label = NULL,
    color_vec = NULL,
    point_size = 0.05,
    point_alpha = 0.8,
    base_font_size = 14
) {

  # -------------------------
  # Input validation
  # -------------------------

  if (!inherits(df, "data.frame")) {
    stop(
      "'df' must be a data.frame or tibble.",
      call. = FALSE
    )
  }

  required_cols <- c(
    dim_1,
    dim_2,
    ct_col,
    dataset_col
  )

  missing_cols <- setdiff(
    required_cols,
    colnames(df)
  )

  if (length(missing_cols) > 0) {
    stop(
      "Missing column(s) in 'df': ",
      paste(missing_cols, collapse = ", "),
      call. = FALSE
    )
  }

  # -------------------------
  # Cell-type handling
  # -------------------------

  ct_levels <- .get_factor_levels(
    df[[ct_col]]
  )

  if (length(ct_levels) == 0) {
    stop(
      "No valid (non-NA) values found in 'ct_col'.",
      call. = FALSE
    )
  }

  df[[ct_col]] <- factor(
    df[[ct_col]],
    levels = ct_levels
  )

  # -------------------------
  # Colours
  # -------------------------

  color_vec <- .validate_colors(
    levels = ct_levels,
    color_vec = color_vec
  )

  # -------------------------
  # Axis labels
  # -------------------------

  if (!is.null(axis_label_base)) {

    x_lab <- paste0(
      axis_label_base,
      "1"
    )

    y_lab <- paste0(
      axis_label_base,
      "2"
    )

  } else {

    x_lab <- dim_1
    y_lab <- dim_2

  }

  color_title <- if (
    is.null(color_label)
  ) {
    ct_col
  } else {
    color_label
  }

  # -------------------------
  # Plot
  # -------------------------

  p <- ggplot2::ggplot(
    df,
    ggplot2::aes(
      x = .data[[dim_1]],
      y = .data[[dim_2]],
      colour = .data[[ct_col]]
    )
  ) +
    ggplot2::geom_point(
      size = point_size,
      alpha = point_alpha
    ) +
    ggplot2::facet_wrap(
      ggplot2::vars(
        .data[[dataset_col]]
      ),
      scales = "free_x"
    ) +
    ggplot2::scale_color_manual(
      values = color_vec,
      drop = FALSE
    ) +
    ggplot2::labs(
      x = x_lab,
      y = y_lab,
      colour = color_title
    ) +
    ggplot2::theme_classic(
      base_size = base_font_size
    ) +
    ggplot2::theme(
      strip.background = ggplot2::element_rect(),
      strip.text = ggplot2::element_text(
        face = "bold",
        size = base_font_size + 2
      ),
      panel.spacing = ggplot2::unit(
        2,
        "lines"
      ),
      axis.line = ggplot2::element_line(
        colour = "black"
      ),
      axis.title = ggplot2::element_text(
        size = base_font_size + 2
      ),
      legend.title = ggplot2::element_text(
        size = base_font_size + 2
      ),
      legend.spacing.y = ggplot2::unit(
        1,
        "cm"
      )
    ) +
    ggplot2::guides(
      colour = ggplot2::guide_legend(
        byrow = TRUE,
        override.aes = list(
          size = 4
        )
      )
    )

  return(p)

}
