#' Example marker-gene expression dataset
#'
#' A simulated single-cell gene expression dataset containing four
#' distinct cell types and twelve marker genes. Each cell type has
#' three dedicated marker genes that are highly expressed within the
#' corresponding cell population and exhibit low background expression
#' in the remaining cell types.
#'
#' The dataset is intended for demonstrating and testing dot plot
#' visualizations, including grouped marker-gene expression summaries
#' generated by `make_marker_dotplot()`.
#'
#' @format A data frame with 800 rows and 13 variables:
#' \describe{
#'   \item{cell_type}{Cell type annotation with four levels:
#'   `"Cell-type A"`, `"Cell-type B"`, `"Cell-type C"`,
#'   and `"Cell-type D"`.}
#'   \item{geneA1}{Marker gene 1 for Cell-type A.}
#'   \item{geneA2}{Marker gene 2 for Cell-type A.}
#'   \item{geneA3}{Marker gene 3 for Cell-type A.}
#'   \item{geneB1}{Marker gene 1 for Cell-type B.}
#'   \item{geneB2}{Marker gene 2 for Cell-type B.}
#'   \item{geneB3}{Marker gene 3 for Cell-type B.}
#'   \item{geneC1}{Marker gene 1 for Cell-type C.}
#'   \item{geneC2}{Marker gene 2 for Cell-type C.}
#'   \item{geneC3}{Marker gene 3 for Cell-type C.}
#'   \item{geneD1}{Marker gene 1 for Cell-type D.}
#'   \item{geneD2}{Marker gene 2 for Cell-type D.}
#'   \item{geneD3}{Marker gene 3 for Cell-type D.}
#' }
#'
#' @details
#' Expression values were simulated such that marker genes show
#' substantially higher expression in their corresponding cell type
#' than in non-target cell types. This structure produces clear and
#' interpretable marker-gene dot plots and serves as a lightweight
#' example dataset for package documentation, examples, and testing.
#'
#' @source Simulated data.
#'
#' @examples
#' head(marker_df)
#'
"marker_df"
